# Generated by Django 5.0.2 on 2024-06-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_work_series_num'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='languages',
            field=models.ManyToManyField(to='core.language'),
        ),
    ]
