# Generated by Django 5.0.6 on 2024-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_savedsearch_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='order_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
