# Generated by Django 5.0.2 on 2024-07-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_savedsearch_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='term',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
