# Generated by Django 2.2.2 on 2019-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cover_alt_text',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_url',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='epub_id',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='process_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='zip_id',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
