# Generated by Django 4.2.4 on 2023-12-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookmark_system_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='copy_work_metadata',
            field=models.BooleanField(default=False),
        ),
    ]
