# Generated by Django 2.2.2 on 2019-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190804_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
