# Generated by Django 4.2.4 on 2023-12-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_copy_work_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_work',
            field=models.BooleanField(default=False),
        ),
    ]
