# Generated by Django 4.2.1 on 2023-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_display_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkcollection',
            old_name='cover_alt_text',
            new_name='header_alt_text',
        ),
        migrations.RenameField(
            model_name='bookmarkcollection',
            old_name='cover_url',
            new_name='header_url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='private_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='public_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkcollection',
            name='private_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkcollection',
            name='public_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
