# Generated by Django 4.2.4 on 2023-12-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usersubscription_subscribed_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
