# Generated by Django 4.2.1 on 2023-06-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cover_alt_text_bookmarkcollection_header_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('attribute_type__name', 'order', 'name')},
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.bookmarkcollection'),
        ),
    ]
