# Generated by Django 2.2.2 on 2019-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190804_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(null=True, to='api.Tag'),
        ),
    ]
