# Generated by Django 4.2.1 on 2023-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attributevalue_options_attributevalue_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourchivesetting',
            name='grouping',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
