# Generated by Django 4.2.4 on 2023-12-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invitation_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_length',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='allow_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_upload_video',
            field=models.BooleanField(default=False),
        ),
    ]
