# Generated by Django 2.2.2 on 2019-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190804_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
