# Generated by Django 4.2.4 on 2024-01-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chapter_video_description_chapter_video_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chive_export_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
