# Generated by Django 4.2.1 on 2023-06-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ourchivesetting_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcollection',
            name='attributes',
            field=models.ManyToManyField(to='api.attributevalue'),
        ),
    ]
