# Generated by Django 4.2.1 on 2023-06-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookmarkcollection_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkcollection',
            name='private_notes',
        ),
        migrations.RemoveField(
            model_name='bookmarkcollection',
            name='public_notes',
        ),
        migrations.AddField(
            model_name='attributetype',
            name='allow_on_bookmark_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmarkcollection',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
