# Generated by Django 2.2.6 on 2019-10-17 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190804_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookmarklink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio_length',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio_url',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image_alt_text',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image_format',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image_url',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chapters', to='api.Work'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
