# Generated by Django 4.2.1 on 2023-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_bookmarkcollection_private_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='contentpage',
            options={'ordering': ('order', 'id')},
        ),
    ]
