# Generated by Django 4.2.4 on 2024-01-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tag_filterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collapse_chapter_video',
            field=models.BooleanField(default=False),
        ),
    ]
