# Generated by Django 2.2.6 on 2019-10-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191017_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='comments',
            field=models.ManyToManyField(to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Bookmark'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_comment_comments_+', to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_alt_text',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='epub_id',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='zip_id',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
