# Generated by Django 4.2.1 on 2023-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_bookmark_options_alter_contentpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
