# Generated by Django 5.0.2 on 2024-02-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_collapse_chapter_video'),
    ]

    def migrate_bookmarks(apps, schema_editor):
        from api.models import BookmarkCollection

        for collection in BookmarkCollection.objects.all():
            for bookmark in collection.bookmarks.all():
                if bookmark.work:
                    collection.works.add(bookmark.work)
            collection.bookmarks.clear()
            collection.save()

    operations = [
        migrations.RunPython(migrate_bookmarks),
    ]
