# Generated by Django 2.2.6 on 2019-10-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191018_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter'),
        ),
    ]
