# Generated by Django 5.0.2 on 2024-02-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usercollection_user_collections_userwork_user_works'),
    ]

    def migrate_user_data(apps, schema_editor):
        from api.models import BookmarkCollection, Work

        for collection in BookmarkCollection.objects.all():
            collection.user.collections.add(collection)
            collection.save()
        for work in Work.objects.all():
            work.user.works.add(work)
            work.save()

    def approve_originating_users(apps, schema_editor):
        from api.models import UserWork, UserCollection

        for uc in UserCollection.objects.all():
            uc.approved = True
            uc.save()
        for uw in UserWork.objects.all():
            uw.approved = True
            uw.save()

    operations = [
        migrations.RunPython(migrate_user_data),
        migrations.RunPython(approve_originating_users),
    ]
