# Generated by Django 2.2.6 on 2019-10-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191018_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='route',
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Chapter'),
        ),
    ]
