# Generated by Django 4.2.1 on 2023-06-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_invitation_send_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='join_reason',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
