# Generated by Django 5.0.2 on 2024-02-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chive_collab_data_migration'),
    ]

    def add_auto_allow_upload(apps, schema_editor):
        from api.models import OurchiveSetting

        if not OurchiveSetting.objects.filter(name='Auto-Allow Upload').exists():
            OurchiveSetting.objects.create(name='Auto-Allow Upload', value='false', valtype='truefalse')

    operations = [
        migrations.RunPython(add_auto_allow_upload),
    ]
