# Generated by Django 2.2.6 on 2019-10-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191019_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='audio_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='chapter_count',
            field=models.IntegerField(default=0),
        ),
    ]
