# Generated by Django 4.2.1 on 2023-06-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_cookies_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='api.attributevalue'),
        ),
    ]
