# Generated by Django 2.2.6 on 2019-10-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191019_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='admin_administrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
