# Generated by Django 4.2.1 on 2023-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_ourchivesetting_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourchivesetting',
            old_name='grouping',
            new_name='valtype',
        ),
        migrations.AlterField(
            model_name='ourchivesetting',
            name='value',
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
