# Generated by Django 5.0.2 on 2024-05-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_language_alter_bookmark_work_bookmark_language_and_more'),
    ]

    def migrate_languages(apps, schema_editor):
        from api.models import BookmarkCollection, Bookmark, Work, Language

        for collection in BookmarkCollection.objects.all():
            for tag in collection.tags.filter(tag_type__label__iexact='Language'):
                language = Language.objects.filter(display_name=tag.display_text).first()
                if language:
                    collection.languages.add(language)
            collection.save()

        for work in Work.objects.all():
            for tag in work.tags.filter(tag_type__label__iexact='Language'):
                language = Language.objects.filter(display_name=tag.display_text).first()
                if language:
                    work.languages.add(language)
            work.save()

        for bookmark in Bookmark.objects.all():
            for tag in bookmark.tags.filter(tag_type__label__iexact='Language'):
                language = Language.objects.filter(display_name=tag.display_text).first()
                if language:
                    bookmark.languages.add(language)
            bookmark.save()

    operations = [
        migrations.RunPython(migrate_languages),
    ]
