# Generated by Django 4.2.1 on 2023-06-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_grouping_ourchivesetting_valtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='preferred_download',
            field=models.CharField(blank=True, choices=[('epub', 'EPUB'), ('m4b', 'M4B'), ('zip', 'ZIP')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourchivesetting',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
