# Generated by Django 2.2.6 on 2019-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191019_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurchiveSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('grouping', models.CharField(max_length=200)),
            ],
        ),
    ]
