# Generated by Django 4.2.1 on 2023-06-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_work_preferred_download_alter_ourchivesetting_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='epub_id',
            new_name='preferred_download_url',
        ),
        migrations.RemoveField(
            model_name='work',
            name='zip_id',
        ),
        migrations.AlterField(
            model_name='work',
            name='preferred_download',
            field=models.CharField(blank=True, choices=[('EPUB', 'EPUB'), ('M4B', 'M4B'), ('ZIP', 'ZIP')], max_length=200, null=True),
        ),
    ]
