# Generated by Django 2.2.6 on 2019-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191019_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='audio_length',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='chapter_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='word_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
