# Generated by Django 4.2.1 on 2023-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_epub_id_work_preferred_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='epub_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='m4b_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='zip_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
