# Generated by Django 5.0.2 on 2024-05-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
