# Generated by Django 4.2.1 on 2023-06-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_work_epub_url_work_m4b_url_work_zip_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_upload_export_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='preferred_download',
            field=models.CharField(blank=True, choices=[('EPUB', 'EPUB'), ('M4B', 'M4B'), ('ZIP', 'ZIP'), ('M4A', 'M4A'), ('MOBI', 'MOBI')], max_length=200, null=True),
        ),
    ]
