# Generated by Django 5.0.2 on 2024-05-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='value',
            new_name='content',
        ),
    ]
