# Generated by Django 2.2.6 on 2019-10-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191019_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_summary',
            new_name='summary',
        ),
    ]
