# Generated by Django 4.2.1 on 2023-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userreportreason_userreport'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userreportreason',
            constraint=models.UniqueConstraint(fields=('reason',), name='unique reportreason'),
        ),
    ]
