# Generated by Django 5.0.2 on 2024-05-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_news_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributetype',
            old_name='show_on_homepage',
            new_name='show_for_browse',
        ),
        migrations.RenameField(
            model_name='tagtype',
            old_name='show_on_homepage',
            new_name='show_for_browse',
        ),
    ]
