# Generated by Django 2.2.6 on 2019-10-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191021_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
