# Generated by Django 4.2.1 on 2023-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userreportreason_unique_reportreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
