# Generated by Django 5.0.2 on 2024-06-04 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_work_series_num_alter_userwork_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='api.workseries'),
        ),
    ]
