# Generated by Django 2.2.6 on 2019-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_chapter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_description',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
