# Generated by Django 4.2.1 on 2023-06-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['resolved', '-updated_on']},
        ),
    ]
