# Generated by Django 2.2.6 on 2019-10-25 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_chapter_audio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='anon_comments_permitted',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='comments_permitted',
        ),
        migrations.CreateModel(
            name='BookmarkCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('cover_url', models.CharField(blank=True, max_length=600, null=True)),
                ('cover_alt_text', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('anon_comments_permitted', models.BooleanField(default=False)),
                ('comments_permitted', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
