# Generated by Django 5.0.2 on 2024-06-06 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usersubscription_subscribed_to_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('header_url', models.CharField(blank=True, max_length=600, null=True)),
                ('header_alt_text', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('system_created_on', models.DateTimeField(auto_now_add=True)),
                ('system_updated_on', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(to='api.attributevalue')),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creating_user', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(to='api.language')),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AnthologyWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=1)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_anthology', to='api.anthology')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anthology_work', to='api.work')),
            ],
            options={
                'db_table': 'api_anthology_works',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='anthology',
            name='works',
            field=models.ManyToManyField(related_name='anthologies', through='api.AnthologyWork', to='api.work'),
        ),
    ]
