# Generated by Django 4.2.1 on 2023-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_userreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcollection',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
