# Generated by Django 5.0.2 on 2024-06-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_anthology_anthologywork_anthology_works'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthology',
            options={'verbose_name_plural': 'anthologies'},
        ),
    ]
