# Generated by Django 5.0.2 on 2024-06-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_anthology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthology',
            name='cover_alt_text',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='anthology',
            name='cover_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
