# Generated by Django 5.0.2 on 2024-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_anthology_cover_alt_text_anthology_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='allow_on_anthology',
            field=models.BooleanField(default=False),
        ),
    ]
