# Generated by Django 4.2.1 on 2023-06-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-updated_on']},
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscribed_to',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_collection',
            field=models.BooleanField(default=False),
        ),
    ]
