# Generated by Django 2.2.6 on 2019-11-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_bookmark_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
