# Generated by Django 5.0.2 on 2024-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_attributetype_allow_on_anthology'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_anthology',
            field=models.BooleanField(default=False),
        ),
    ]
