# Generated by Django 5.0.2 on 2024-06-10 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_usersubscription_subscribed_to_anthology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthology',
            name='owners',
        ),
        migrations.CreateModel(
            name='UserAnthology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('Anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anthology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_anthologies',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='anthology',
            name='users',
            field=models.ManyToManyField(through='api.UserAnthology', to=settings.AUTH_USER_MODEL),
        ),
    ]
