# Generated by Django 4.2.1 on 2023-07-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_comment_remodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcomment',
            name='bookmark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.bookmark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.chapter'),
            preserve_default=False,
        ),
    ]
