# Generated by Django 4.2.1 on 2023-07-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_bookmarkcomment_bookmark_chaptercomment_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcollection',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CollectionComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.comment')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.bookmarkcollection')),
            ],
            bases=('api.comment',),
        ),
    ]
