# Generated by Django 5.0.2 on 2024-06-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_anthology_owners_useranthology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anthology',
            old_name='users',
            new_name='owners',
        ),
    ]
