# Generated by Django 3.1 on 2020-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200510_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='audio_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
