# Generated by Django 4.2.4 on 2023-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_contentpage_locked_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
