# Generated by Django 4.1 on 2022-08-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_fingergun_delete_fingerguns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingergun',
            name='count',
        ),
    ]
