# Generated by Django 4.2.4 on 2023-08-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_adminannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tagtype',
            options={'ordering': ('sort_order', 'label')},
        ),
        migrations.AddField(
            model_name='attributetype',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
