# Generated by Django 4.2.4 on 2023-08-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_attributetype_options_alter_tagtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag_type__sort_order', 'tag_type__label')},
        ),
    ]
