# Generated by Django 4.1 on 2022-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_fingergun_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='fingerguns',
            field=models.IntegerField(default=0),
        ),
    ]
