# Generated by Django 4.2.4 on 2023-08-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='user',
            name='default_work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.worktype'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
