# Generated by Django 4.2.4 on 2023-08-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_worktype_options_user_default_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.worktype'),
        ),
    ]
