# Generated by Django 4.2.4 on 2023-08-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_user_default_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='end_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
