# Generated by Django 4.2.4 on 2023-08-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_chapter_end_notes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tagtype',
            name='api_tagtype_label_bb5e2f_idx',
        ),
        migrations.AddField(
            model_name='tagtype',
            name='type_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='tagtype',
            index=models.Index(fields=['type_name'], name='api_tagtype_type_na_56cb9e_idx'),
        ),
    ]
