# Generated by Django 4.2.4 on 2023-08-17 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_tagtype_api_tagtype_label_bb5e2f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingergun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
