# Generated by Django 4.2.1 on 2023-05-09 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0042_userblocklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBlockList',
            new_name='UserBlocks',
        ),
    ]
