# Generated by Django 4.2.4 on 2023-08-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_fingergun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collapse_chapter_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='collapse_chapter_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='collapse_chapter_text',
            field=models.BooleanField(default=False),
        ),
    ]
