# Generated by Django 4.2.1 on 2023-05-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_userblocklist_userblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='anon_comments_permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='comments_permitted',
            field=models.BooleanField(default=False),
        ),
    ]
