# Generated by Django 4.2.4 on 2023-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_user_collapse_chapter_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='homepage_include',
            field=models.BooleanField(default=True),
        ),
    ]
