# Generated by Django 4.2.1 on 2023-05-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_bookmark_anon_comments_permitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookmarkcomment',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.bookmark'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
