# Generated by Django 4.2.4 on 2023-08-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_tagtype_homepage_include'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagtype',
            old_name='homepage_include',
            new_name='filterable',
        ),
    ]
