# Generated by Django 4.2.1 on 2023-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_notification_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('read',)},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
