# Generated by Django 4.2.4 on 2023-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_bookmarkcollection_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='show_in_aggregate',
            field=models.BooleanField(default=True),
        ),
    ]
