# Generated by Django 4.2.4 on 2023-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_contentpage_agree_on_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminannouncement',
            options={'ordering': ('active', 'expires_on')},
        ),
        migrations.AddField(
            model_name='adminannouncement',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
