# Generated by Django 4.2.1 on 2023-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_bookmark_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_text',
            field=models.CharField(default='', max_length=120),
        ),
    ]
