# Generated by Django 4.2.4 on 2023-09-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_adminannouncement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminannouncement',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
