# Generated by Django 4.2.1 on 2023-05-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_tag_display_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
