# Generated by Django 4.2.4 on 2023-10-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_adminannouncement_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Empty comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
