# Generated by Django 4.2.1 on 2023-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_chapter_comment_count_work_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
