# Generated by Django 4.2.1 on 2023-05-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_bookmark_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='anon_comments_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='comments_permitted',
            field=models.BooleanField(default=True),
        ),
    ]
