# Generated by Django 4.2.4 on 2023-10-07 20:17

from django.db import migrations, models
import django_registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_comment_text_alter_work_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, and digits only.', max_length=150, unique=True, validators=[django_registration.validators.ReservedNameValidator()], verbose_name='Username'),
        ),
    ]
