# Generated by Django 4.2.1 on 2023-05-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_bookmark_anon_comments_permitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
