# Generated by Django 4.2.1 on 2023-05-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_ourchiveadmincontent_alter_bookmark_draft_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurchiveAdminContent',
            new_name='ContentPage',
        ),
    ]
