# Generated by Django 4.2.1 on 2023-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_rename_ourchiveadmincontent_contentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='label',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
