# Generated by Django 4.2.1 on 2023-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_tag_text_alter_tagtype_label'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['text'], name='api_tag_text_e39765_idx'),
        ),
        migrations.AddIndex(
            model_name='tagtype',
            index=models.Index(fields=['label'], name='api_tagtype_label_bb5e2f_idx'),
        ),
    ]
