# Generated by Django 4.2.1 on 2023-06-03 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_tag_api_tag_text_e39765_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_email', models.CharField(max_length=200)),
                ('invite_token', models.CharField(max_length=200)),
                ('token_expiration', models.DateTimeField()),
                ('token_used', models.BooleanField(default=False)),
            ],
        ),
    ]
