# Generated by Django 4.2.1 on 2023-06-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='user_email',
            new_name='email',
        ),
    ]
