# Generated by Django 4.2.1 on 2023-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_rename_user_email_invitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='register_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
