# Generated by Django 4.2.1 on 2023-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_invitation_register_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag_type__label',)},
        ),
        migrations.AlterModelOptions(
            name='tagtype',
            options={'ordering': ('label',)},
        ),
        migrations.AddField(
            model_name='invitation',
            name='send_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
