# Generated by Django 4.2.1 on 2023-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_tag_options_alter_tagtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('text', 'tag_type')},
        ),
    ]
