# Generated by Django 4.2.1 on 2023-06-04 20:04

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_tag_text_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('text'), descending=True), models.F('tag_type_id'), name='unique_text_and_type'),
        ),
    ]
