# Generated by Django 4.2.1 on 2023-06-04 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_tag_unique_together_tag_unique_text_and_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('allow_on_work', models.BooleanField(default=False)),
                ('allow_on_bookmark', models.BooleanField(default=False)),
                ('allow_on_chapter', models.BooleanField(default=False)),
                ('allow_on_user', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='api.attributetype')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='attributetype',
            index=models.Index(fields=['name'], name='api_attribu_name_8fc968_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributetype',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('name'), descending=True), name='unique_attributetype_name'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='attributes',
            field=models.ManyToManyField(to='api.attributevalue'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='attributes',
            field=models.ManyToManyField(to='api.attributevalue'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attributes',
            field=models.ManyToManyField(to='api.attributevalue'),
        ),
        migrations.AddField(
            model_name='work',
            name='attributes',
            field=models.ManyToManyField(to='api.attributevalue'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['name'], name='api_attribu_name_0a819d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('name'), descending=True), name='unique_attributevalue_name'),
        ),
    ]
