# Generated by Django 4.2.1 on 2023-06-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_attributetype_attributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='allow_multiselect',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WorkAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributevalue')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.work')),
            ],
        ),
    ]
