# Generated by Django 4.2.1 on 2023-06-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_attributetype_allow_multiselect_workattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('attribute_type__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='workattribute',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='ChapterAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributevalue')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
            ],
            options={
                'ordering': ['attribute_value'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributevalue')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookmark')),
            ],
        ),
    ]
