version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  OURCHIVE_DB_NAME: "ourchive"
  OURCHIVE_DB_USER: "${OURCHIVE_DB_USER}"
  OURCHIVE_DB_PASSWORD: "${OURCHIVE_DB_PW}"
  OURCHIVE_DB_HOST: "ourchive-db"
  # Web settings
  SECRET_KEY: "${OURCHIVE_SECRET_KEY}"
  OURCHIVE_SITES_SCHEME: "http"
  OURCHIVE_ROOT_URL: "${OURCHIVE_ROOT_URL}"
  # Email settings.
  # EMAIL_BACKEND: "django.core.mail.backends.${EMAIL_BACKEND}.EmailBackend"
  # DEFAULT_FROM_EMAIL: "${EMAIL_DEFAULT_FROM}"
  # EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
  # EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
  # EMAIL_HOST: "${EMAIL_HOST}"
  # EMAIL_PORT: "${EMAIL_PORT}"
  # EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  # EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"

x-volumes:
  &default-back-volumes
  - ourchive-static-data:/ourchive_app/static
  - ourchive-media-data:/ourchive_app/media

services:
  ourchive-db:
    image: postgres:16.8
    environment:
      POSTGRES_DB: "ourchive"
      POSTGRES_USER: "${OURCHIVE_DB_USER}"
      POSTGRES_PASSWORD: "${OURCHIVE_DB_PW}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${OURCHIVE_DB_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - ourchive-db-data:/var/lib/postgresql/data
    networks:
      - ourchive

  ourchive:
    image: ourchive:latest
    #build: .
    #container_name: ourchive
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - ourchive
    depends_on:
      ourchive-db:
        condition: service_healthy

  ourchive-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./ourchive-gateway/ourchive.conf:/etc/nginx/conf.d/default.conf
      - ourchive-static-data:/ourchive_app/static
      - ourchive-media-data:/ourchive_app/media
    networks:
      - ourchive
    depends_on:
      - ourchive

volumes:
  ourchive-static-data:
  ourchive-media-data:
  ourchive-db-data:

networks:
  ourchive: