# Generated by Django 5.0.2 on 2024-05-04 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    def migrate_languages(apps, schema_editor):
        from core.models import BookmarkCollection, Bookmark, Work, Language

        for collection in BookmarkCollection.objects.all():
            for tag in collection.tags.filter(tag_type__label__iexact='Language'):
                language = Language.objects.filter(display_name=tag.display_text).first()
                if language:
                    collection.languages.add(language)
            collection.save()

        for work in Work.objects.all():
            for tag in work.tags.filter(tag_type__label__iexact='Language'):
                language = Language.objects.filter(display_name=tag.display_text).first()
                if language:
                    work.languages.add(language)
            work.save()

        for bookmark in Bookmark.objects.all():
            for tag in bookmark.tags.filter(tag_type__label__iexact='Language'):
                language = Language.objects.filter(display_name=tag.display_text).first()
                if language:
                    bookmark.languages.add(language)
            bookmark.save()

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('display_name', models.CharField(max_length=200)),
                ('ietf_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.work'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_languages',
            field=models.ManyToManyField(related_name='users', to='core.language'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='languages',
            field=models.ManyToManyField(to='core.language'),
        ),
        migrations.AddField(
            model_name='bookmarkcollection',
            name='languages',
            field=models.ManyToManyField(to='core.language'),
        ),
        migrations.AddField(
            model_name='work',
            name='languages',
            field=models.ManyToManyField(to='core.language'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.RenameField(
            model_name='contentpage',
            old_name='value',
            new_name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name='attributetype',
            old_name='show_on_homepage',
            new_name='show_for_browse',
        ),
        migrations.RenameField(
            model_name='tagtype',
            old_name='show_on_homepage',
            new_name='show_for_browse',
        ),
        migrations.AddField(
            model_name='work',
            name='series_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_users', to='core.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worktype'),
        ),
        migrations.CreateModel(
            name='WorkSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('system_created_on', models.DateTimeField(auto_now_add=True)),
                ('system_updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='core.workseries'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='core.workseries'),
        ),
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('header_url', models.CharField(blank=True, max_length=600, null=True)),
                ('header_alt_text', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('system_created_on', models.DateTimeField(auto_now_add=True)),
                ('system_updated_on', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(to='core.attributevalue')),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creating_user', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(to='core.language')),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AnthologyWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=1)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_anthology', to='core.anthology')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anthology_work', to='core.work')),
            ],
            options={
                'db_table': 'core_anthology_works',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='anthology',
            name='works',
            field=models.ManyToManyField(related_name='anthologies', through='core.AnthologyWork', to='core.work'),
        ),
        migrations.AlterModelOptions(
            name='anthology',
            options={'verbose_name_plural': 'anthologies'},
        ),
        migrations.AddField(
            model_name='anthology',
            name='cover_alt_text',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='anthology',
            name='cover_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='allow_on_anthology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to_anthology',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='anthology',
            name='owners',
        ),
        migrations.CreateModel(
            name='UserAnthology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('Anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anthology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_anthologies',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='anthology',
            name='users',
            field=models.ManyToManyField(through='core.UserAnthology', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='anthology',
            old_name='users',
            new_name='owners',
        ),
        migrations.RenameField(
            model_name='useranthology',
            old_name='Anthology',
            new_name='anthology',
        ),
        migrations.AlterField(
            model_name='useranthology',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_anthologies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_languages),
    ]
