# Generated by Django 5.0.2 on 2024-06-18 15:48

import django.core.validators
import django.db.models.functions.text
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_searchgroup_options_searchgroup_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchgroup',
            name='label',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('display_name'), descending=True), name='unique_language_display_name'),
        ),
    ]
