# Generated by Django 5.0.2 on 2024-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['name'], name='core_attrib_name_1f8730_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['text'], name='core_tag_text_734fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='attributetype',
            index=models.Index(fields=['name'], name='core_attrib_name_eb0dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='tagtype',
            index=models.Index(fields=['type_name'], name='core_tagtyp_type_na_7d086e_idx'),
        ),
    ]
