# Generated by Django 5.0.2 on 2024-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='type_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
