# Generated by Django 5.0.2 on 2024-06-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tag_text_alter_tagtype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourchivesetting',
            name='name',
            field=models.CharField(choices=[('Search Provider', 'Search Provider'), ('Upload Endpoint', 'Upload Endpoint'), ('Registration Permitted', 'Registration Permitted'), ('Invite Only', 'Invite Only'), ('Use Invite Queue', 'Use Invite Queue'), ('Invite Queue Limit', 'Invite Queue Limit'), ('Default Icon URL', 'Default Icon URL'), ('Audio Processing', 'Audio Processing'), ('Rating Star Count', 'Rating Star Count'), ('Allow Comments', 'Allow Comments'), ('Ratings Enabled', 'Ratings Enabled'), ('Auto-Allow Upload', 'Auto-Allow Upload')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ourchivesetting',
            name='valtype',
            field=models.CharField(blank=True, choices=[('truefalse', 'truefalse'), ('choice', 'choice')], max_length=200, null=True),
        ),
    ]
