# Generated by Django 5.0.2 on 2024-06-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ourchivesetting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, default='icon-default.png', max_length=600, null=True),
        ),
    ]
