# Generated by Django 5.0.2 on 2024-06-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, default='/static/icon-default.png', max_length=600, null=True),
        ),
    ]
