# Generated by Django 5.0.6 on 2024-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_news_embed_in_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourchivesetting',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
