# Generated by Django 5.0.6 on 2025-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tag_tag_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_text_and_type',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('text', 'tag_type_id'), name='unique_text_and_type'),
        ),
    ]
