# Generated by Django 5.0.6 on 2025-04-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_tag_unique_text_and_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_on', '-updated_on'), 'verbose_name_plural': 'news'},
        ),
    ]
