# Generated by Django 5.0.6 on 2025-04-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, default='CHANGEME', max_length=600, null=True),
        ),
    ]
