# Generated by Django 5.0.6 on 2025-08-03 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-updated_on'], 'verbose_name': 'Subscribed user', 'verbose_name_plural': 'Subscribed users'},
        ),
        migrations.CreateModel(
            name='UserCollectionSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookmarkcollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscribed collection',
                'verbose_name_plural': 'Subscribed collections',
                'db_table': 'core_usercollectionsubscription',
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.work')),
            ],
            options={
                'verbose_name': 'Subscribed work',
                'verbose_name_plural': 'Subscribed works',
                'db_table': 'core_userworksubscription',
                'ordering': ['-updated_on'],
            },
        ),
    ]
