# Generated by Django 5.0.6 on 2025-08-03 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworksubscription',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_work_subscriptions', to='core.work'),
        ),
    ]
