# Generated by Django 5.2.6 on 2025-09-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_userworksubscription_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionsubscription',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='core.bookmarkcollection'),
        ),
    ]
