# Generated by Django 5.2.6 on 2026-03-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_usercollectionsubscription_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcollection',
            name='locked_to_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='locked_to_users',
            field=models.BooleanField(default=False),
        ),
    ]
