# Generated by Django 5.2.6 on 2026-07-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bookmarkcollection_locked_to_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
