# Generated by Django 4.2.4 on 2023-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_objectmapping_remove_workimport_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimport',
            name='job_processing',
            field=models.BooleanField(default=False),
        ),
    ]
