# Generated by Django 4.2.4 on 2023-08-07 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_workimport_job_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimport',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
