# Generated by Django 4.2.4 on 2023-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_workimport_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmapping',
            name='object_type',
            field=models.CharField(choices=[('work', 'work'), ('chapter', 'chapter'), ('work_type', 'work_type')], max_length=100),
        ),
    ]
