# Generated by Django 4.2.4 on 2024-01-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0007_additionalmapping_objectmapping_additional_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiveExport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('job_message', models.TextField()),
                ('job_success', models.BooleanField(default=True)),
                ('job_finished', models.BooleanField(default=False)),
                ('job_processing', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('export_works', models.BooleanField(default=True)),
                ('export_bookmarks', models.BooleanField(default=True)),
                ('export_collections', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
