# Generated by Django 5.0.2 on 2024-06-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_chiveexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiveexport',
            name='export_anthologies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chiveexport',
            name='export_series',
            field=models.BooleanField(default=True),
        ),
    ]
