ALTER TABLE api_adminannouncement RENAME TO core_adminannouncement; 
ALTER TABLE api_contentpage RENAME TO core_contentpage; 
ALTER TABLE api_invitation RENAME TO core_invitation; 
ALTER TABLE api_ourchivesetting RENAME TO core_ourchivesetting; 
ALTER TABLE api_attributetype RENAME TO core_attributetype; 
ALTER TABLE api_attributevalue RENAME TO core_attributevalue; 
ALTER TABLE api_bookmarkattribute RENAME TO core_bookmarkattribute; 
ALTER TABLE api_bookmarkcollection RENAME TO core_bookmarkcollection; 
ALTER TABLE api_comment RENAME TO core_comment; 
ALTER TABLE api_bookmarklink RENAME TO core_bookmarklink; 
ALTER TABLE api_chapterattribute RENAME TO core_chapterattribute; 
ALTER TABLE api_message RENAME TO core_message; 
ALTER TABLE api_notification RENAME TO core_notification; 
ALTER TABLE api_notificationtype RENAME TO core_notificationtype; 
ALTER TABLE api_tag RENAME TO core_tag; 
ALTER TABLE api_tagtype RENAME TO core_tagtype; 
ALTER TABLE api_userattribute RENAME TO core_userattribute; 
ALTER TABLE api_userblocks RENAME TO core_userblocks; 
ALTER TABLE api_user_collections RENAME TO core_user_collections; 
ALTER TABLE api_userreport RENAME TO core_userreport; 
ALTER TABLE api_userreportreason RENAME TO core_userreportreason; 
ALTER TABLE api_usersubscription RENAME TO core_usersubscription; 
ALTER TABLE api_user_works RENAME TO core_user_works; 
ALTER TABLE api_work RENAME TO core_work; 
ALTER TABLE api_fingergun RENAME TO core_fingergun; 
ALTER TABLE api_chapter RENAME TO core_chapter; 
ALTER TABLE api_bookmark RENAME TO core_bookmark; 
ALTER TABLE api_workattribute RENAME TO core_workattribute; 
ALTER TABLE api_worktype RENAME TO core_worktype; 
ALTER TABLE api_user RENAME TO core_user; 
ALTER TABLE api_bookmarkcomment RENAME TO core_bookmarkcomment; 
ALTER TABLE api_chaptercomment RENAME TO core_chaptercomment; 
ALTER TABLE api_collectioncomment RENAME TO core_collectioncomment; 
ALTER TABLE api_user_groups RENAME TO core_user_groups; 
ALTER TABLE api_user_user_permissions RENAME TO core_user_user_permissions; 
ALTER TABLE api_user_attributes RENAME TO core_user_attributes; 
ALTER TABLE api_bookmark_attributes RENAME TO core_bookmark_attributes; 
ALTER TABLE api_bookmarkcollection_attributes RENAME TO core_bookmarkcollection_attributes; 
ALTER TABLE api_chapter_attributes RENAME TO core_chapter_attributes; 
ALTER TABLE api_message_replies RENAME TO core_message_replies; 
ALTER TABLE api_bookmarkcollection_tags RENAME TO core_bookmarkcollection_tags; 
ALTER TABLE api_bookmark_tags RENAME TO core_bookmark_tags; 
ALTER TABLE api_work_attributes RENAME TO core_work_attributes; 
ALTER TABLE api_work_tags RENAME TO core_work_tags; 
ALTER TABLE api_bookmarkcollection_works RENAME TO core_bookmarkcollection_works;

UPDATE django_content_type SET app_label = 'core' WHERE app_label = 'api';

INSERT INTO django_migrations(app, name, applied) VALUES ('core', '0001_initial', Now());

DELETE FROM django_migrations WHERE app = 'api';