name: "Production App Deploy"

on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: "Copies production branch to ourchive-production server"
        env:
          remote_host: ${{ secrets.PROD_DEPLOY_HOST }}
          remote_port: ${{ secrets.PROD_DEPLOY_PORT }}
          remote_user: ${{ secrets.PROD_DEPLOY_USER }}
          remote_key: ${{ secrets.PROD_DEPLOY_KEY }}
          prod_env_file: ${{ secrets.PROD_ENV_FILE }}
          local_dir: "ourchive_app"
          remote_dir: "/var/www/ourchive"
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          sudo apt-get install python3-pip python3-dev
          sudo -H pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install django
          pip install -r ourchive_app/requirements.txt
          python ourchive_app/manage.py collectstatic
          rsync -avzr -e "ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
          rm ~/.ssh/id_github
      - name: Execute Python Script
        uses: appleboy/ssh-action@v0.1.10
        env:
          remote_host: ${{ secrets.PROD_DEPLOY_HOST }}
          remote_port: ${{ secrets.PROD_DEPLOY_PORT }}
          remote_user: ${{ secrets.PROD_DEPLOY_USER }}
          remote_key: ${{ secrets.PROD_DEPLOY_KEY }}
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.PROD_DEPLOY_USER }}
          key: ${{ secrets.PROD_DEPLOY_KEY }}
          port: ${{ secrets.PROD_DEPLOY_PORT }}
          script: cd /home/ourchive && bash deploy.sh
