name: Run Python tests

on: [push]

jobs:
  build:
    name: Run UI Tests against Deployed Site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Chicago"
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 
            'ourchive-app/ui-tests'
            'ourchive-app/requirements.txt'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements.txt
        run: pip install -r requirements.txt
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true